export const COMMON_STRINGS = {
  email: {
    en: "Email",
    es: "Correo electrónico",
    fr: "Email",
    hi: "ईमेल",
  },
  password: {
    en: "Password",
    es: "Contraseña",
    fr: "Mot de passe",
    hi: "पासवर्ड",
  },
  rememberMe: {
    en: "Remember me",
    es: "Recuérdame",
    fr: "Souviens-toi de moi",
    hi: "मुझे याद रखें",
  },
  forgotPassword: {
    en: "Forgot password?",
    es: "¿Olvidaste tu contraseña?",
    fr: "Mot de passe oublié?",
    hi: "पासवर्ड भूल गए?",
  },
  or: {
    en: "or",
    es: "o",
    fr: "ou",
    hi: "या",
  },
  signIn: {
    en: "Sign in",
    es: "Iniciar sesión",
    fr: "Se connecter",
    hi: "साइन इन करें",
  },
  signUp: {
    en: "Sign up",
    es: "Regístrate",
    fr: "S'inscrire",
    hi: "साइन अप करें",
  },
  jobs: {
    en: "Jobs",
    es: "Trabajos",
    fr: "Emplois",
    hi: "नौकरियां",
  },
  myApplications: {
    en: "My Applications",
    es: "Mis aplicaciones",
    fr: "Mes applications",
    hi: "मेरे आवेदन",
  },
  messages: {
    en: "Messages",
    es: "Mensajes",
    fr: "Messages",
    hi: "संदेश",
  },
  searchJobs: {
    en: "Search Jobs",
    es: "Buscar trabajos",
    fr: "Rechercher des emplois",
    hi: "नौकरियां खोजें",
  },
  profile: {
    en: "Profile",
    es: "Perfil",
    fr: "Profil",
    hi: "प्रोफ़ाइल",
  },
  settings: {
    en: "Settings",
    es: "Configuración",
    fr: "Paramètres",
    hi: "सेटिंग्स",
  },
  changeLanguage: {
    en: "Change Language",
    es: "Cambiar idioma",
    fr: "Changer de langue",
    hi: "भाषा बदलें",
  },
  signOut: {
    en: "Sign Out",
    es: "Desconectar",
    fr: "Se déconnecter",
    hi: "साइन आउट",
  },
  filters: {
    en: "Filters",
    es: "Filtros",
    fr: "Filtres",
    hi: "फ़िल्टर",
  },
  ago: {
    en: "ago",
    es: "hace",
    fr: "il y a",
    hi: "पहले",
  },
  years: {
    en: "years",
    es: "años",
    fr: "ans",
    hi: "साल",
  },
  months: {
    en: "months",
    es: "meses",
    fr: "mois",
    hi: "महीने",
  },
  days: {
    en: "days",
    es: "días",
    fr: "journées",
    hi: "दिन",
  },
  hours: {
    en: "hours",
    es: "horas",
    fr: "heures",
    hi: "घंटे",
  },
  minutes: {
    en: "minutes",
    es: "minutos",
    fr: "minutes",
    hi: "मिनट",
  },
  seconds: {
    en: "seconds",
    es: "segundos",
    fr: "secondes",
    hi: "सेकंड",
  },
  to: {
    en: "to",
    es: "a",
    fr: "à",
    hi: "से",
  },
  details: {
    en: "Details",
    es: "Detalles",
    fr: "Détails",
    hi: "विवरण",
  },
  at: {
    en: "at",
    es: "en",
    fr: "à",
    hi: "पर",
  },
  submit: {
    en: "Submit",
    es: "Enviar",
    fr: "Soumettre",
    hi: "प्रस्तुत करें",
  },
};
