export const COMMON_STRINGS = {
  email: {
    en: "Email",
    es: "Correo electrónico",
    fr: "Email",
    hi: "ईमेल",
  },
  password: {
    en: "Password",
    es: "Contraseña",
    fr: "Mot de passe",
    hi: "पासवर्ड",
  },
  rememberMe: {
    en: "Remember me",
    es: "Recuérdame",
    fr: "Souviens-toi de moi",
    hi: "मुझे याद रखें",
  },
  forgotPassword: {
    en: "Forgot password?",
    es: "¿Olvidaste tu contraseña?",
    fr: "Mot de passe oublié?",
    hi: "पासवर्ड भूल गए?",
  },
  or: {
    en: "or",
    es: "o",
    fr: "ou",
    hi: "या",
  },
  signIn: {
    en: "Sign in",
    es: "Iniciar sesión",
    fr: "Se connecter",
    hi: "साइन इन करें",
  },
  signUp: {
    en: "Sign up",
    es: "Regístrate",
    fr: "S'inscrire",
    hi: "साइन अप करें",
  },
  jobs: {
    en: "Jobs",
    es: "Trabajos",
    fr: "Emplois",
    hi: "नौकरियां",
  },
  myApplications: {
    en: "My Applications",
    es: "Mis aplicaciones",
    fr: "Mes applications",
    hi: "मेरे आवेदन",
  },
  messages: {
    en: "Messages",
    es: "Mensajes",
    fr: "Messages",
    hi: "संदेश",
  },
  searchJobs: {
    en: "Search Jobs",
    es: "Buscar trabajos",
    fr: "Rechercher des emplois",
    hi: "नौकरियां खोजें",
  },
  profile: {
    en: "Profile",
    es: "Perfil",
    fr: "Profil",
    hi: "प्रोफ़ाइल",
  },
  settings: {
    en: "Settings",
    es: "Configuración",
    fr: "Paramètres",
    hi: "सेटिंग्स",
  },
  changeLanguage: {
    en: "Change Language",
    es: "Cambiar idioma",
    fr: "Changer de langue",
    hi: "भाषा बदलें",
  },
  signOut: {
    en: "Sign Out",
    es: "Desconectar",
    fr: "Se déconnecter",
    hi: "साइन आउट",
  },
  filters: {
    en: "Filters",
    es: "Filtros",
    fr: "Filtres",
    hi: "फ़िल्टर",
  },
  ago: {
    en: "ago",
    es: "hace",
    fr: "il y a",
    hi: "पहले",
  },
  years: {
    en: "years",
    es: "años",
    fr: "ans",
    hi: "साल",
  },
  months_string: {
    en: "months",
    es: "meses",
    fr: "mois",
    hi: "महीने",
  },
  days: {
    en: "days",
    es: "días",
    fr: "journées",
    hi: "दिन",
  },
  hours: {
    en: "hours",
    es: "horas",
    fr: "heures",
    hi: "घंटे",
  },
  minutes: {
    en: "minutes",
    es: "minutos",
    fr: "minutes",
    hi: "मिनट",
  },
  seconds: {
    en: "seconds",
    es: "segundos",
    fr: "secondes",
    hi: "सेकंड",
  },
  to: {
    en: "to",
    es: "a",
    fr: "à",
    hi: "से",
  },
  details: {
    en: "Details",
    es: "Detalles",
    fr: "Détails",
    hi: "विवरण",
  },
  at: {
    en: "at",
    es: "en",
    fr: "à",
    hi: "पर",
  },
  submit: {
    en: "Submit",
    es: "Enviar",
    fr: "Soumettre",
    hi: "प्रस्तुत करें",
  },
  send: {
    en: "Send",
    es: "Enviar",
    fr: "Envoyer",
    hi: "भेजें",
  },
  applied: {
    en: "Applied",
    es: "Aplicado",
    fr: "Appliqué",
    hi: "लागू",
  },
  published: {
    en: "Published",
    es: "Publicado",
    fr: "Publié",
    hi: "प्रकाशित",
  },
  full_name: {
    en: "Full Name",
    es: "Nombre completo",
    fr: "Nom complet",
    hi: "पूरा नाम",
  },
  email_address: {
    en: "Email Address",
    es: "Dirección de correo electrónico",
    fr: "Adresse e-mail",
    hi: "ईमेल पता",
  },
  max: {
    en: "max",
    es: "máx",
    fr: "max",
    hi: "अधिकतम",
  },
  save: {
    en: "Save",
    es: "Guardar",
    fr: "Sauvegarder",
    hi: "सहेजें",
  },
  select: {
    en: "Select",
    es: "Seleccionar",
    fr: "Sélectionner",
    hi: "चुनें",
  },
  months: {
    january: {
      en: "January",
      es: "Enero",
      fr: "Janvier",
      hi: "जनवरी",
    },
    february: {
      en: "February",
      es: "Febrero",
      fr: "Février",
      hi: "फरवरी",
    },
    march: {
      en: "March",
      es: "Marzo",
      fr: "Mars",
      hi: "मार्च",
    },
    april: {
      en: "April",
      es: "Abril",
      fr: "Avril",
      hi: "अप्रैल",
    },
    may: {
      en: "May",
      es: "Mayo",
      fr: "Mai",
      hi: "मई",
    },
    june: {
      en: "June",
      es: "Junio",
      fr: "Juin",
      hi: "जून",
    },
    july: {
      en: "July",
      es: "Julio",
      fr: "Juillet",
      hi: "जुलाई",
    },
    august: {
      en: "August",
      es: "Agosto",
      fr: "Août",
      hi: "अगस्त",
    },
    september: {
      en: "September",
      es: "Septiembre",
      fr: "Septembre",
      hi: "सितंबर",
    },
    october: {
      en: "October",
      es: "Octubre",
      fr: "Octobre",
      hi: "अक्टूबर",
    },
    november: {
      en: "November",
      es: "Noviembre",
      fr: "Novembre",
      hi: "नवंबर",
    },
    december: {
      en: "December",
      es: "Diciembre",
      fr: "Décembre",
      hi: "दिसंबर",
    },
  },
  yes: {
    en: "Yes",
    es: "Sí",
    fr: "Oui",
    hi: "हां",
  },
  no: {
    en: "No",
    es: "No",
    fr: "Non",
    hi: "नहीं",
  },
  logged_out_message: {
    en: "You have been logged out",
    es: "Has cerrado sesión",
    fr: "Vous avez été déconnecté",
    hi: "आप लॉग आउट हो गए हैं",
  },
  logged_in_message: {
    en: "You have been logged in",
    es: "Has iniciado sesión",
    fr: "Vous avez été connecté",
    hi: "आप लॉग इन हो गए हैं",
  },
  registration_success_message: {
    en: "Registration successful, please login to continue",
    es: "Registro exitoso, inicie sesión para continuar",
    fr: "Inscription réussie, veuillez vous connecter pour continuer",
    hi: "पंजीकरण सफल, कृपया जारी रखने के लिए लॉगिन करें",
  },
  personal_information: {
    en: "Personal Information",
    es: "Información personal",
    fr: "Informations personnelles",
    hi: "व्यक्तिगत जानकारी",
  },
  about_me: {
    en: "About Me",
    es: "Sobre mí",
    fr: "À propos de moi",
    hi: "मेरे बारे में",
  },
  skills: {
    en: "Skills",
    es: "Habilidades",
    fr: "Compétences",
    hi: "कौशल",
  },
  institution_name: {
    en: "Institution Name",
    es: "Nombre de la institución",
    fr: "Nom de l'institution",
    hi: "संस्थान का नाम",
  },
  location: {
    en: "Location",
    es: "Ubicación",
    fr: "Lieu",
    hi: "स्थान",
  },
  field_of_study: {
    en: "Field of Study",
    es: "Campo de estudio",
    fr: "Domaine d'étude",
    hi: "अध्ययन का क्षेत्र",
  },
  education: {
    en: "Education",
    es: "Educación",
    fr: "Éducation",
    hi: "शिक्षा",
  },
  experience: {
    en: "Experience",
    es: "Experiencia",
    fr: "Expérience",
    hi: "अनुभव",
  },
  company_name: {
    en: "Company Name",
    es: "Nombre de la empresa",
    fr: "Nom de l'entreprise",
    hi: "कंपनी का नाम",
  },
  role: {
    en: "Role",
    es: "Rol",
    fr: "Rôle",
    hi: "भूमिका",
  },
  currently_working: {
    en: "Currently working here",
    es: "Actualmente trabajando aquí",
    fr: "Actuellement en poste ici",
    hi: "वर्तमान में यहां काम कर रहे हैं",
  },
  phone_number: {
    en: "Phone Number",
    es: "Número de teléfono",
    fr: "Numéro de téléphone",
    hi: "फोन नंबर",
  },
  invalid_credentials_message: {
    en: "Invalid credentials, please try again",
    es: "Credenciales inválidas, inténtelo de nuevo",
    fr: "Informations d'identification invalides, veuillez réessayer",
    hi: "अमान्य परिचय, कृपया पुन: प्रयास करें",
  },
};
