export const JOB_DESCRIPTION_PAGE_STRINGS = {
  jobDescription: {
    en: "Job Description",
    es: "Descripción del trabajo",
    fr: "Description du poste",
    hi: "नौकरी का विवरण",
  },
  requirements: {
    en: "Requirements",
    es: "Requerimientos",
    fr: "Exigences",
    hi: "आवश्यकताएं",
  },
  aboutTheCompany: {
    en: "About the Company",
    es: "Sobre la empresa",
    fr: "À propos de l'entreprise",
    hi: "कंपनी के बारे में",
  },
  companyReviews: {
    en: "Company Reviews",
    es: "Reseñas de la empresa",
    fr: "Avis sur l'entreprise",
    hi: "कंपनी समीक्षा",
  },
  totalReviews: {
    en: "Total Reviews",
    es: "Reseñas totales",
    fr: "Avis total",
    hi: "कुल समीक्षा",
  },
  averageRating: {
    en: "Average Rating",
    es: "Calificación promedio",
    fr: "Note moyenne",
    hi: "औसत रेटिंग",
  },
  timeFlexibility: {
    en: "Time Flexibility",
    es: "Flexibilidad de tiempo",
    fr: "Flexibilité du temps",
    hi: "समय की लचीलापन",
  },
  benefits: {
    en: "Benefits",
    es: "Beneficios",
    fr: "Avantages",
    hi: "लाभ",
  },
  payScale: {
    en: "Pay Scale",
    es: "Escala salarial",
    fr: "Échelle des salaires",
    hi: "वेतन स्केल",
  },
  workEnvironment: {
    en: "Work Environment",
    es: "Ambiente de trabajo",
    fr: "Environnement de travail",
    hi: "कार्य वातावरण",
  },
  writeReview: {
    en: "Leave a review",
    es: "Dejar una reseña",
    fr: "Laisser un avis",
    hi: "समीक्षा छोड़ें",
  },
  posted: {
    en: "Posted",
    es: "Publicado",
    fr: "Posté",
    hi: "पोस्ट किया गया",
  },
  applyNow: {
    en: "Apply Now",
    es: "Aplica ahora",
    fr: "Postuler maintenant",
    hi: "अभी आवेदन करें",
  },
  saveForLater: {
    en: "Save for Later",
    es: "Guardar para más tarde",
    fr: "Enregistrer pour plus tard",
    hi: "बाद में सुरक्षित करें",
  },
};
