export const PROFILE_EDIT_PAGE_STRINGS = {
  personal: {
    en: "Personal",
    es: "Personal",
    fr: "Personnel",
    hi: "व्यक्तिगत",
  },
  full_name_message: {
    en: "Your full name which will be visible to everyone",
    es: "Su nombre completo que será visible para todos",
    fr: "Votre nom complet qui sera visible de tous",
    hi: "आपका पूरा नाम जो सभी को दिखाई देगा",
  },
  profile_url: {
    en: "Profile URL",
    es: "URL del perfil",
    fr: "URL du profil",
    hi: "प्रोफ़ाइल URL",
  },
  profile_url_message: {
    en: "Your profile URL which you can share",
    es: "Su URL de perfil que puede compartir",
    fr: "Votre URL de profil que vous pouvez partager",
    hi: "आपका प्रोफ़ाइल URL जिसे आप साझा कर सकते हैं",
  },
  email_address_message: {
    en: "Your email address which will be visible to recruiters",
    es: "Su dirección de correo electrónico que será visible para los reclutadores",
    fr: "Votre adresse e-mail qui sera visible par les recruteurs",
    hi: "आपका ईमेल पता जो रिक्रूटर्स को दिखाई देगा",
  },
  phone_number: {
    en: "Phone Number",
    es: "Número de teléfono",
    fr: "Numéro de téléphone",
    hi: "फ़ोन नंबर",
  },
  phone_number_message: {
    en: "Your number used for sending updates and notifications",
    es: "Su número utilizado para enviar actualizaciones y notificaciones",
    fr: "Votre numéro utilisé pour envoyer des mises à jour et des notifications",
    hi: "अपडेट और सूचनाएं भेजने के लिए आपका नंबर",
  },
  profile_picture: {
    en: "Profile Picture",
    es: "Foto de perfil",
    fr: "Photo de profil",
    hi: "प्रोफ़ाइल चित्र",
  },
  profile_picture_message: {
    en: "Your profile picture which will be visible to everyone",
    es: "Su foto de perfil que será visible para todos",
    fr: "Votre photo de profil qui sera visible de tous",
    hi: "आपका प्रोफ़ाइल चित्र जो सभी को दिखाई देगा",
  },
  click_to_upload: {
    en: "Click to upload",
    es: "Haga clic para cargar",
    fr: "Cliquez pour télécharger",
    hi: "अपलोड करने के लिए क्लिक करें",
  },
  career: {
    en: "Career",
    es: "Carrera",
    fr: "Carrière",
    hi: "करियर",
  },
  about_me: {
    en: "About Me",
    es: "Sobre mí",
    fr: "À propos de moi",
    hi: "मेरे बारे में",
  },
  about_me_message: {
    en: "Talk about your professional life in few words",
    es: "Hable sobre su vida profesional en pocas palabras",
    fr: "Parlez de votre vie professionnelle en quelques mots",
    hi: "कुछ शब्दों में अपने पेशेवर जीवन के बारे में बात करें",
  },
  skills: {
    en: "Skills",
    es: "Habilidades",
    fr: "Compétences",
    hi: "कौशल",
  },
  skills_message: {
    en: "Include the skills and technologies you're familiar with",
    es: "Incluya las habilidades y tecnologías con las que está familiarizado",
    fr: "Incluez les compétences et technologies avec lesquelles vous êtes familier",
    hi: "शामिल करें जिन कौशलों और प्रौद्योगिकियों का आपको ज्ञान है",
  },
  click_to_upload: {
    en: "Click to upload",
    es: "Haga clic para cargar",
    fr: "Cliquez pour télécharger",
    hi: "अपलोड करने के लिए क्लिक करें",
  },
  resume: {
    en: "Resume",
    es: "currículum",
    fr: "CV",
    hi: "रिज्यूम",
  },
  resume_message: {
    en: "Your resume will be forwarded to companies when you apply",
    es: "Su currículum se enviará a las empresas cuando se postule",
    fr: "Votre CV sera transmis aux entreprises lorsque vous postulez",
    hi: "जब आप आवेदन करेंगे तो आपका रिज्यूम कंपनियों को फॉरवर्ड किया जाएगा",
  },
  education: {
    en: "Education",
    es: "Educación",
    fr: "Éducation",
    hi: "शिक्षा",
  },
  institution_name: {
    en: "Institution Name",
    es: "Nombre de la institución",
    fr: "Nom de l'institution",
    hi: "संस्थान का नाम",
  },
  institution_name_message: {
    en: "Name of the institution you studied",
    es: "Nombre de la institución en la que estudiaste",
    fr: "Nom de l'institution où vous avez étudié",
    hi: "वह संस्थान का नाम जहाँ आपने अध्ययन किया",
  },
  location: {
    en: "Location",
    es: "Ubicación",
    fr: "Emplacement",
    hi: "स्थान",
  },
  location_message: {
    en: "Location of the institution",
    es: "Ubicación de la institución",
    fr: "Emplacement de l'institution",
    hi: "संस्थान का स्थान",
  },
  from: {
    en: "From",
    es: "De",
    fr: "De",
    hi: "से",
  },
  from_message: {
    en: "Starting month and year",
    es: "Mes y año de inicio",
    fr: "Mois et année de début",
    hi: "आरंभ करने का महीना और वर्ष",
  },
  select_month: {
    en: "Select Month",
    es: "Seleccionar mes",
    fr: "Sélectionner le mois",
    hi: "महीना चुनें",
  },
  select_year: {
    en: "Select Year",
    es: "Seleccionar año",
    fr: "Sélectionner l'année",
    hi: "वर्ष चुनें",
  },
  to: {
    en: "To",
    es: "A",
    fr: "À",
    hi: "तक",
  },
  to_message: {
    en: "Ending month and year",
    es: "Mes y año de finalización",
    fr: "Mois et année de fin",
    hi: "समाप्ति महीना और वर्ष",
  },
  currently_studying: {
    en: "Currently studying here",
    es: "Actualmente estudiando aquí",
    fr: "Étudie actuellement ici",
    hi: "वर्तमान में यहाँ पढ़ाई कर रहा हूँ",
  },
  education_level_title: {
    en: "Education Level",
    es: "Nivel educativo",
    fr: "Niveau d'éducation",
    hi: "शिक्षा स्तर",
  },
  education_level_message: {
    en: "Level of education you have achieved",
    es: "Nivel de educación que has alcanzado",
    fr: "Niveau d'éducation que vous avez atteint",
    hi: "आपने प्राप्त किया शिक्षा स्तर",
  },
  education_level: {
    middle_school: {
      en: "Middle School",
      es: "Escuela intermedia",
      fr: "Collège",
      hi: "मध्य विद्यालय",
    },
    high_school: {
      en: "High School",
      es: "Escuela secundaria",
      fr: "Lycée",
      hi: "उच्च विद्यालय",
    },
    associate_degree: {
      en: "Associate Degree",
      es: "Título de asociado",
      fr: "Diplôme d'associé",
      hi: "सहायक डिग्री",
    },
    bachelors_degree: {
      en: "Bachelor's Degree",
      es: "Título de licenciatura",
      fr: "Licence",
      hi: "स्नातक की डिग्री",
    },
    masters_degree: {
      en: "Master's Degree",
      es: "Título de maestría",
      fr: "Maîtrise",
      hi: "स्नातकोत्तर की डिग्री",
    },
    doctorate: {
      en: "Doctorate",
      es: "Doctorado",
      fr: "Doctorat",
      hi: "डॉक्टरेट",
    },
  },
  fields_list: {
    information_technology: {
      en: "Information Technology",
      es: "Tecnología de la información",
      fr: "Technologies de l'information",
      hi: "सूचना प्रौद्योगिकी",
    },
    business: {
      en: "Business",
      es: "Negocios",
      fr: "Entreprise",
      hi: "व्यापार",
    },
    arts: {
      en: "Arts",
      es: "Artes",
      fr: "Arts",
      hi: "कला",
    },
    science: {
      en: "Science",
      es: "Ciencia",
      fr: "Science",
      hi: "विज्ञान",
    },
    engineering: {
      en: "Engineering",
      es: "Ingeniería",
      fr: "Ingénierie",
      hi: "इंजीनियरिंग",
    },
    medical: {
      en: "Medical",
      es: "Médico",
      fr: "Médical",
      hi: "मेडिकल",
    },
    law: {
      en: "Law",
      es: "Ley",
      fr: "Loi",
      hi: "कानून",
    },
    social_science: {
      en: "Social Science",
      es: "Ciencias sociales",
      fr: "Sciences sociales",
      hi: "सामाजिक विज्ञान",
    },
    other: {
      en: "Other",
      es: "Otro",
      fr: "Autre",
      hi: "अन्य",
    },
  },
  fields_list_message: {
    en: "Select the field you studied",
    es: "Seleccione el campo que estudió",
    fr: "Sélectionnez le domaine que vous avez étudié",
    hi: "वह क्षेत्र चुनें जिसमें आपने अध्ययन किया",
  },
  experience: {
    en: "Experience",
    es: "Experiencia",
    fr: "Expérience",
    hi: "अनुभव",
  },
  company_name: {
    en: "Company Name",
    es: "Nombre de la empresa",
    fr: "Nom de l'entreprise",
    hi: "कंपनी का नाम",
  },
  company_name_message: {
    en: "Name of the company you worked",
    es: "Nombre de la empresa en la que trabajaste",
    fr: "Nom de l'entreprise où vous avez travaillé",
    hi: "वह कंपनी का नाम जिसमें आपने काम किया",
  },
  company_location_message: {
    en: "Location of the company",
    es: "Ubicación de la empresa",
    fr: "Emplacement de l'entreprise",
    hi: "कंपनी का स्थान",
  },
  role: {
    en: "Role",
    es: "Rol",
    fr: "Rôle",
    hi: "भूमिका",
  },
  role_message: {
    en: "Your role in the company",
    es: "Tu papel en la empresa",
    fr: "Votre rôle dans l'entreprise",
    hi: "कंपनी में आपकी भूमिका",
  },
  field: {
    en: "Field",
    es: "Campo",
    fr: "Champ",
    hi: "क्षेत्र",
  },
  field_message: {
    en: "Field of your work",
    es: "Campo de tu trabajo",
    fr: "Domaine de votre travail",
    hi: "आपके काम का क्षेत्र",
  },
  currently_working: {
    en: "Currently working here",
    es: "Actualmente trabajando aquí",
    fr: "Travaille actuellement ici",
    hi: "वर्तमान में यहाँ काम कर रहा हूँ",
  },
};
