import StoreWrapper from "@/utils/StoreWrapper";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import SessionProviderClient from "@/utils/SessionProviderClient";
import LoginProvider from "@/utils/LoginProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SessionProviderClient>
          <StoreWrapper>
            <LoginProvider>
              <TooltipProvider delayDuration={100}>{children}</TooltipProvider>
            </LoginProvider>
          </StoreWrapper>
        </SessionProviderClient>
      </body>
    </html>
  );
}
