import StoreWrapper from "@/utils/StoreWrapper";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreWrapper>
          <TooltipProvider delayDuration={100}>{children}</TooltipProvider>
        </StoreWrapper>
      </body>
    </html>
  );
}
