import StoreWrapper from "@/utils/StoreWrapper";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreWrapper>{children}</StoreWrapper>
      </body>
    </html>
  );
}
